### ISSUE TITLE
Both roaming partners trust the clearing house ?

### ISSUE THREAD

**Issue by simplerun** [e-clearing-net/OCHP#9]
Initial communication between partners goes through clearing house. It is written that "Both roaming partners trust the clearing house", question is - How is it accomplished ?
My guess is that the clearing house store partners endpoint info as DirectEndpoint class instance. And every partner store the clearing house endpoint info as DirectEndpoint class instance also.
IMO it is necessary to have clear proposal of that data types. Didn't find it in the documentation.
Another question, how partner provide that data to the clearing house and how the clearing house provide that data to every partner ?
My guess here (one of) is that a partner log in into the clearing house web site and then clearing house send email with his data.

**Comment by mtdern** [comment]
It is a precondition that partners trust the clearing house -  this is the entire basis for the OCHP communication. Since OCHPdirect is an extension to OCHP, a functional OCHP connection to the clearing house is a precondition. This also requires that the partner has a usage contract with the clearing house (which enables this trust) and an acceptance tested implementation before being issued access credentials (to the clearing house OCHP webservice).

**Comment by simplerun** [comment]
It is fine for me.
And please, add that statement into the documentation.

**Comment by Mookuh** [comment]
Added a statement about both parties requiring the OCHP connection to the clearing house.
